id = "phasmid-theme"
name = "Phasmid"
schema_version = 1
version = "1.0.0"
authors = ["Thijs Lander <contact@thijslander.com>"]
description = "Neutral theme that blends with application UI's such as Obsidian and Figma, using Jetbrains syntax colors."
repository = "https://github.com/t-lander/phasmid-zed"
